### PR TITLE
Remove CDI dependencies

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by radcortez** [comment]
It has to be removed because it would create a circular dependency between CDI and Config, assuming that we want to keep the goal of having Jakarta Config in the Core profile and have every other specification depend on it (including CDI to configure itself).

I think a better alternative is when CDI adopts Config, the requirements, and TCKs should be added in the CDI specification directly. Or in the Core Profile Specification.

**Comment by Emily-Jiang** [comment]
We can create a separate module to store these kind of tests, build a separate jar and it will be much easier to move later.

**Comment by radcortez** [comment]
We can still do all the CDI work and move it later to the CDI spec or Core profile spec, as long as the Config specification and resulting binaries do not reference CDI in any way.

**Comment by jansupol** [comment]
The Config dependency can be in the provided scope and picked up with CDI

**Comment by Emily-Jiang** [comment]
We agreed to put the tests in the Jakarta EE core profile for these kind of integration tests when we are ready to put up for a release.

**Review by jansupol — APPROVED** [review]

**Pull request merged**
